version: "3.8"

services:
    redis:
        image: redis:7-alpine
        container_name: redis
        command: ["redis-server", "--appendonly", "yes"]  # bật AOF để có persistence
        volumes:
          - redis-data:/data
        ports:
          - "6379:6379"         
        healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          interval: 5s
          timeout: 3s
          retries: 10
        networks:
          - backend-net

    frontend:
       build:
         context: .
         dockerfile: frontend.dockerfile
       container_name: frontend
       env_file:
         - ./.env.docker
       environment:
         ASPNETCORE_ENVIRONMENT: "docker"
         OCELOT__BASEURL: "https://gateway:8080"
         
       volumes:
         - ./certs/aspnetapp.pfx:/app/certs/aspnetapp.pfx:ro
         - ../logs:/app/logs:rw
       ports:
         - "7286:8080"
       networks:
         - backend-net        

volumes:
  redis-data: {} 

networks:
  backend-net:
    external: true
    driver: bridge
    name: backend_backend-net

